// Ereignis- und DOM-Regressionen ohne Browser oder externe Netzwerkverbindung.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class Node {constructor(tag){this.tag=tag;this.children=[];this.listeners={};this.attrs={};this.dataset={};this.isConnected=true;this.textContent='';}append(...ns){this.children.push(...ns);ns.forEach(n=>n.parent=this);}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}addEventListener(k,f){this.listeners[k]=f;}focus(){this.focused=true;}querySelector(s){return this.map?.[s]||this.querySelectorAll(s)[0]||null;}querySelectorAll(s){if(this.lists?.[s])return this.lists[s];const all=[];function visit(n){for(const c of n.children){if((s==='img'&&c.tag==='img')||(s==='strong'&&c.tag==='strong')||(s==='p'&&c.tag==='p')||(s==='.brand-art'&&c.className?.includes('brand-art')))all.push(c);visit(c);}}visit(this);return all;}}
const load=(file,ctx)=>vm.runInContext(fs.readFileSync(file,'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),ctx);
// Maskottchen: genau fünf Bilder, keine Duplikate, Sprachwechsel ohne Austausch der Bildknoten.
const targets={};for(const s of ['#identity','#universe > .wrap','#world'])targets[s]=new Node('section');
const events={};let lang='de';const doc={querySelector:s=>targets[s],createElement:t=>new Node(t),addEventListener:(n,f)=>{events[n]=f;}};
const ctx=vm.createContext({document:doc,getLanguage:()=>lang});load('dist/brand-art.js',ctx);vm.runInContext('installBrandArt()',ctx);
const imgs=Object.values(targets).flatMap(n=>n.querySelectorAll('img'));assert.equal(imgs.length,5);assert.equal(new Set(imgs.map(n=>n.src)).size,5);assert(imgs.every(n=>n.loading==='lazy'&&n.decoding==='async'&&n.width>0&&n.height>0));
lang='en';events['lyvra:languagechange']();assert(imgs.every(n=>n.alt.includes('LYVRA')));assert(imgs[0].alt.includes('chrome emblem'));vm.runInContext('installBrandArt()',ctx);assert.equal(Object.values(targets).flatMap(n=>n.querySelectorAll('img')).length,5);
// Chat: XSS-Text wird nicht als HTML ausgeführt; Geschichte ist begrenzt und löschbar.
const root=new Node('div'),log=new Node('div'),input=new Node('input'),form=new Node('form'),submit=new Node('button'),reset=new Node('button');root.map={'.chat-demo-log':log,input,form,'[type="submit"]':submit,'[data-demo-reset]':reset};const labels=['badge','notice','title','link'].map(key=>{const n=new Node('span');n.dataset.demoText=key;return n;});const suggestions=[0,1,2].map(i=>{const n=new Node('button');n.dataset.demoSuggestion=String(i);return n;});root.lists={'[data-demo-text]':labels,'[data-demo-suggestion]':suggestions};const chatEvents={};const chatDoc={querySelector:()=>root,createElement:t=>new Node(t),addEventListener:(n,f)=>chatEvents[n]=f};lang='de';const chat=vm.createContext({document:chatDoc,getLanguage:()=>lang});load('dist/chat-demo.js',chat);vm.runInContext('installChatDemo()',chat);assert.equal(input.disabled,false);assert.equal(submit.disabled,false);
input.value='<img src=x onerror=alert(1)>';form.listeners.submit({preventDefault(){}});assert(log.children[1].children[1].textContent.includes('<img'));assert(!('innerHTML' in log.children[1].children[1]));for(let i=0;i<30;i++)suggestions[0].listeners.click();assert.equal(log.children.length,41);lang='en';chatEvents['lyvra:languagechange']();assert(log.children[0].children[1].textContent.startsWith('Discover'));assert(labels[0].textContent.includes('NO LIVE AI'));reset.listeners.click();assert.equal(log.children.length,1);
// Sprachwahl bleibt bei gesperrtem localStorage funktionsfähig.
const text={nodeValue:'Datenschutz',isConnected:true};let first=true;const controls={};for(const s of ['#language','[for="language"]','.menu','meta[name="description"]','.nav'])controls[s]=new Node('div');controls['.menu'].setAttribute('aria-expanded','false');const languageEvents=[];const i18nDoc={body:{},documentElement:{},createTreeWalker:()=>({currentNode:text,nextNode(){if(first){first=false;return true;}return false;}}),querySelector:s=>controls[s]||null,dispatchEvent:e=>languageEvents.push(e)};const language=vm.createContext({document:i18nDoc,NodeFilter:{SHOW_TEXT:4},CustomEvent:class{constructor(type,detail){this.type=type;this.detail=detail;}},localStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}});load('dist/i18n.js',language);vm.runInContext('initializeLanguage();setLanguage("en");',language);assert.equal(text.nodeValue,'Privacy Policy');assert.equal(i18nDoc.documentElement.lang,'en');assert.equal(controls['.menu'].attrs['aria-label'],'Open menu');vm.runInContext('setLanguage("de");',language);assert.equal(text.nodeValue,'Datenschutz');assert.equal(languageEvents.length,3);
console.log('PASS: five brand images + duplicate guard + DE/EN; chat XSS text, bounded/reset history + DE/EN; language works with blocked storage. Headless DOM only.');
